spring.application.name=processor

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/payment
spring.r2dbc.username=payment
spring.r2dbc.password=payment

# For Liquibase migrations
spring.datasource.url=jdbc:postgresql://localhost:5432/payment
spring.datasource.username=payment
spring.datasource.password=payment
spring.datasource.driver-class-name=org.postgresql.Driver

# Liquibase Configuration
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

# Camel Configuration - Keep application running
camel.main.run-controller=true
camel.main.duration-max-messages=0
camel.main.duration-max-idle-seconds=0

# Kafka Configuration (used by Camel)
kafka.bootstrap-servers=localhost:9092
kafka.consumer.group-id=payment-processor-group
kafka.topic.payment=payment-topic
kafka.topic.payment-status=payment-status

management.otlp.metrics.export.enabled=false

# Enable R2DBC logging
# logging.level.io.r2dbc.postgresql.QUERY=DEBUG
# logging.level.io.r2dbc.postgresql.PARAM=DEBUG
# logging.level.org.springframework.r2dbc=DEBUG
# logging.level.org.springframework.transaction=DEBUG