spring.application.name=payment-service
payment.topic=payment-topic
payment.status.topic=payment-status
payment.status.consumer.group=payment-service-status-consumer
kafka.brokers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}

management.otlp.metrics.export.enabled=false